// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_CmojL61SEid5uzUguSwdwpRQ_SzWAA',
    appId: '1:891317652376:web:d6129abca6362ddd78b9ed',
    messagingSenderId: '891317652376',
    projectId: 'project-uas-pam-cd642',
    authDomain: 'project-uas-pam-cd642.firebaseapp.com',
    storageBucket: 'project-uas-pam-cd642.firebasestorage.app',
    measurementId: 'G-EEPB7J2P5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu5k4JlDo6fs36ybRA7zONmeg3aTfOVkc',
    appId: '1:891317652376:android:3208a37f1bf0159078b9ed',
    messagingSenderId: '891317652376',
    projectId: 'project-uas-pam-cd642',
    storageBucket: 'project-uas-pam-cd642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqNJidayN2rweVXTuwaGUmhqUZmei6dOo',
    appId: '1:891317652376:ios:305f78c4c05a772b78b9ed',
    messagingSenderId: '891317652376',
    projectId: 'project-uas-pam-cd642',
    storageBucket: 'project-uas-pam-cd642.firebasestorage.app',
    iosBundleId: 'com.example.m05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqNJidayN2rweVXTuwaGUmhqUZmei6dOo',
    appId: '1:891317652376:ios:305f78c4c05a772b78b9ed',
    messagingSenderId: '891317652376',
    projectId: 'project-uas-pam-cd642',
    storageBucket: 'project-uas-pam-cd642.firebasestorage.app',
    iosBundleId: 'com.example.m05',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_CmojL61SEid5uzUguSwdwpRQ_SzWAA',
    appId: '1:891317652376:web:0c8902f059106fef78b9ed',
    messagingSenderId: '891317652376',
    projectId: 'project-uas-pam-cd642',
    authDomain: 'project-uas-pam-cd642.firebaseapp.com',
    storageBucket: 'project-uas-pam-cd642.firebasestorage.app',
    measurementId: 'G-PWGT6MB8X5',
  );
}
